Cette fiche résume quelques unes des fonctions essentielles applicables
à des listes.

* Fonctions du premier ordre
  :PROPERTIES:
  :CUSTOM_ID: fonctions-du-premier-ordre
  :END:

** \hs{(++) :: [a] -> [a] -> [a]}
   :PROPERTIES:
   :CUSTOM_ID: section
   :END:

est l'opérateur de concaténation: \hs{"Hask" ++ "ell" == "Haskell"}.

** \hs{take :: Int -> [a] -> [a]}
   :PROPERTIES:
   :CUSTOM_ID: section-1
   :END:

renvoie les $n$ premiers éléments de la liste, ou la liste si sa taille
est inférieure à $n$: \hs{take 3 [1..10] == [1,2,3]} ;
\hs{take 100 [1,2] == [1,2]}

** \hs{drop :: Int -> [a] -> [a]}
   :PROPERTIES:
   :CUSTOM_ID: section-2
   :END:

renvoie la liste moins les $n$ premiers éléments, ou la liste vide si sa
taille est inférieure à $n$: \hs{drop 3 [1..6] == [4,5,6]} ;
\hs{drop 100 [1,2] == []}

* Fonctions d'ordre supérieur
  :PROPERTIES:
  :CUSTOM_ID: fonctions-dordre-supérieur
  :END:

** \hs{takeWhile :: (a -> Bool) -> [a] -> [a]}
   :PROPERTIES:
   :CUSTOM_ID: section-3
   :END:

est similaire à \hsFn{take}, mais renvoie la tête de la liste jusqu'à la
dernière valeur pour laquelle la condition est vraie:
\hs{takeWhile (<5) [1..8] == [1,2,3,4]}

** \hs{dropWhile :: (a -> Bool) -> [a] -> [a]}
   :PROPERTIES:
   :CUSTOM_ID: section-4
   :END:

est similaire à \hsFn{take}, mais renvoie la queue de la liste à partir
de la première valeur pour laquelle la condition est fausse:
\hs{dropWhile (<5) [1..8] == [5,6,7,8]}

** \hs{map :: (a -> b) -> [a] -> [b]}
   :PROPERTIES:
   :CUSTOM_ID: section-5
   :END:

applique une fonction à chaque élément d'une liste:
\hs{map (*2) [1,2,3] == [2,4,6]}.

\box{warn} \hsFn{map} existe pour des raisons historiques. Préférez-lui
\qsee{\hsFn{fmap}}{fn:fmap}, qui s'applique à n'importe quel
\qsee{foncteur}{Functor} et pas uniquement aux listes. \endbox

** \hs{head :: [a] -> a}
   :PROPERTIES:
   :CUSTOM_ID: section-6
   :END:

renvoie le premier élément de la liste, ou génère une exception si la
liste est vide.

** \hs{last :: [a] -> a}
   :PROPERTIES:
   :CUSTOM_ID: section-7
   :END:

renvoie le dernier élément de la liste, ou génère une exception si la
liste est vide.

** \hs{tail :: [a] -> [a]}
   :PROPERTIES:
   :CUSTOM_ID: section-8
   :END:

Lorem ipsum

** \hs{zip :: [a] -> [b] -> [(a, b)]}
   :PROPERTIES:
   :CUSTOM_ID: section-9
   :END:

Lorem ipsum

** \hs{zip3 :: [a] -> [b] -> [c] -> [(a, b, c)]}
   :PROPERTIES:
   :CUSTOM_ID: section-10
   :END:

Lorem ipsum

** \hs{zipWith :: (a -> b -> c) -> [a] -> [b] -> [c]}
   :PROPERTIES:
   :CUSTOM_ID: section-11
   :END:

Lorem ipsum

** \hs{zipWith3 :: (a -> b -> c -> d) -> [a] -> [b] -> [c] -> [d]}
   :PROPERTIES:
   :CUSTOM_ID: section-12
   :END:

Lorem ipsum
