























Une fonction se définit de la façon suivante:

#begin_src haskell
add :: a -> b -- Signature de type, généralement optionnel. add x = expr
x #end_src

Une fonction infixe se définit en entourant son nom de parenthèses,
comme pour l'utiliser en préfixe:

#begin_src haskell
(+/) a b = a + b + a / b #end_src

* Fonctions locales
  :PROPERTIES:
  :CUSTOM_ID: fonctions-locales
  :END:

On peut définir des fonctions dont la visibilité est limitée à une
fonction. C'est utile pour définir des constantes, ou fournir des
fonctions utilitaires qui n'ont pas besoin d'être disponibles au niveau
du module. Haskell propose deux syntaxes: ~let~, qui place les
variables locales /avant/ le code de la fonction, et ~where~, qui les
positionne /après/.

\begin{halfwidth}
#begin_src haskell
circLet :: Fractional a => a -> a
circLet radius = let pi   = 3.14
                     diam = 2 * radius
                 in pi * diam
#end_src
\end{halfwidth}
\hfill%
\begin{halfwidth}
    #begin_src haskell
circWhere :: Fractional a => a -> a
circWhere radius = pi * diam
    where pi   = 3.141592653589793
          diam = 2 * radius
    #end_src
\end{halfwidth}
\begin{itemize}
\item Le choix de l'une ou de l'autre syntaxe est une question de lisibilité.
\item On peut les imbriquer: une fonction définie dans une clause ~let~/~where~ peut à son tour définir des fonctions locales, etc.
\item La visiblité des fonctions locales est limitée à la définition englobante.
\end{itemize}
* Fixité (précédence et associativité)
  :PROPERTIES:
  :CUSTOM_ID: fixité-précédence-et-associativité
  :END:

\label{defining-fixity}

L'associativité et la précédence sont collectivement nommées «fixité».
La fixité d'une fonction infixe (et de n'importe quelle fonction préfixe
dans sa forme infixe, comme ~`elem`~) est fixée par une déclaration
~infixl~ (associatif à gauche), ~infixr~ (associatif à droite) ou
~infix~ (non-associatif ), suivie de l'ordre de précédence compris
entre 0 et 9 et du nom de la fonction:

#begin_src haskell
(+/) :: Num a => a -> a -> a infixl 9 +/ (+/) a b = a + b + a / b #end_src

Il est possible de définir la fixité d'une fonction locale, directement
dans la clause ~let~ ou ~where~ où elle est définie.
